#Replication-controller creates multiple instances of pods.  (nested of 2 definition files).
apiVersion: v1
kind: ReplicationController
metadata:                                                 # replication controller
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:           # whats inside object we are creating that need to be mentioned in spec.    # replication controller
  template:
      metadata:                              ## pod
        name: myapp-pod  # pod name
        labels:
          app: myapp
          type: front-end
     spec:                                    #pod
        containers:
      - name: nginx-container  # container name
        image: nginx                         ##

 replicas:                               # input how many replicas we need

  #note:
  #template and replicas are sibings of spec so theu must be in same vertical line.
  # we create a template section under spec to provide a pod template to be used by the replication controller to create replicas.
  # move all the content of the pod defintion file into template section of the replication controller except apiVersion and kind.
  
# to crete replication controller use below command:
kubectl create -f rc-defintion.yaml
when replication controller is created , it first creates the pods using pod definition template as many as required.
