apiVersion: v1
kind: Service
metadata:
  name: myapp-service   // service name
spec:
  type: NodePort         // service type
  ports:
    - targetPort: 80   # Port on the pod where the application is running       
      port: 80         # Port exposed inside the cluster (service port)
      nodePort: 30008  # Port exposed on each Node's IP (external access)
  selector:                  // many pod many have 80 port so pod lables we need to mention.
    app: myapp
    type: front-end


service mapped to single pod we know:
when multiple pods:
