apiVersion: apps/v1
kind: Deployment
metadata:                                                 
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:           # whats inside object we are creating that need to be mentioned in spec.    
  template:
      metadata:                              ## pod
        name: myapp-pod  # pod name
        labels:
          app: myapp
          type: front-end
     spec:                                    #pod
        containers:
      - name: nginx-container  # container name
        image: nginx                         ##

 replicas: 3                               # input how many replicas we need
 selector:
   matchLabels:  # used to match the labels specified under labels on the pod.
     type: front-end


     commands:
     to create deployment:
kubectl create -f deployment-defintion.yaml
(when deployment is created automatically replicaset is created with deployment name)
replicationset automatically creates pods
kubectl get pods

to see list of deployment:
kubectl get deployments

kubectl get replicaset

kubectl get all
deployment
replicaset
pods
